### ISSUE TITLE
Implement dynamic loop counting

### ISSUE THREAD

**Issue by lukasrothenberger** [discopop-project/discopop#155]
Currently, the output of `loop_counter_output.txt` is filled with dummys (`1000`).
Since the loop counting will most probably become a relevant feature for the upcoming pattern filtering / ranking, this should be fixed.

**Comment by goerlibe** [comment]
TODO:

- [ ] implementation
- [ ] test
- [ ] documentation (docs/Pattern_Detection/Patterns/Do-All.md + wherever we document the command line options)

**Comment by lukasrothenberger** [comment]
Note: iterations for some loops can be determined statically. It would be a good idea to store this information and ignore such loops in the instrumentation. To get the correct results in the end, nesting of loops has to be considered and the total amount of iterations adjusted accordingly.
