### ISSUE TITLE
docs(quickstart example): add "how to interpret the suggested patterns" section

### ISSUE THREAD

**Issue by goerlibe** [discopop-project/discopop#179]
docs/Pattern_Detection/DiscoPoPExplorer says:

_A simple walk-through example for the execution of the DiscoPoP Explorer and the interpretation and implementation of the results can be found as part of our [quickstart example](../Quickstart/Example.md)._

but the example is missing this information.

I suggest to show source and transformed source as snippets and then add a short paragraph that describes the changes that had to be made.

**Comment by lukasrothenberger** [comment]
you're right. good idea.
