### ISSUE TITLE
build: better detection of llvm

### ISSUE THREAD

**Issue by goerlibe** [discopop-project/discopop#205]
building on the server does currently not work

it should be possible to specify one of the installed versions of llvm.

this improvement will likely lead to an interface change: `cmake -DLLVM_DIST_PATH` might get replaced, cmake required version might change

Checklist:

- [x] works with a single llvm installation
- [x] works with multiple versions of llvm installed
- [x] works with llvm 11.0
- [x] works with llvm 11.1
- [x] possibility to specify a specific version when multiple versions are installed
- [x] works with llvm built from source by specifying build directory

**Comment by lukasrothenberger** [comment]
LLVM 11.0 and 11.1 seem to be incompatible...

"So I guess it does not make sense to request 11.x if 11.0.x and 11.1.x are API-incompatible"

https://stackoverflow.com/questions/66305592/how-to-match-major-version-only-in-cmake
