### ISSUE TITLE
Rename Data.xml to cus.xml

### ISSUE THREAD

**Issue by lukasrothenberger** [discopop-project/discopop#415]
Todo: 
- update occurrences of files named `Data.xml` in the repository to `cus.xml` 
- update all occurrences of `Data.xml` in the code to `cus.xml`

**Comment by Krunal-375** [comment]
Can you assign me this task I will love to do it for my beginner level open source contribution. Just assign me this task and I will send you the pull request

**Comment by lukasrothenberger** [comment]
Hi Krunal,
sure, thank you very much for your help!
I will update the issue description to be a bit more detailed.

Best
Lukas
