### ISSUE TITLE
properly cleanup .discopop before running

### ISSUE THREAD

**Issue by goerlibe** [discopop-project/discopop#464]
We should be able to rerun all the tools and they should properly cleanup the .discopop directory before the execution so that leftover files of previous executions are removed and do not mess with the results.

Most tools already behave as expected, however some might not.

To close, 
- [x] make sure that every tool works as expected even if there are (possibly outdated) leftovers of previous executions inside .discopop

**Comment by lukasrothenberger** [comment]
linked to #467
