### ISSUE TITLE
False positive pragma generation

### ISSUE THREAD

**Issue by JShim-CS** [discopop-project/discopop#604]
@lukasrothenberger 

The following code generates a false-positive omp pragma for the last for loop in main.
Pragma generated: "  #pragma omp parallel for shared(Arr,N) reduction(+:w)"

```
#include <stdio.h>

int f(int i){
  if(i < 100000/2){
    return i + 100000/2;
  }else{
    return i;
  }
}

int g(int i){
  return i;
}


int main() {
  int N = 100000;
  int Arr[N];
  

  for (int i = 0; i < N; i++) {
    Arr[i] = 0;
  }

  long w = 0;

  for(int i = 0; i < N; i++){
    w += Arr[g(i)];
    Arr[f(i)] = 1;
  }

}


```

**Comment by lukasrothenberger** [comment]
Hi @JShim-CS,
the reported false positive should be fixed in the linked branch.
If you can find the time, could you please validate it?
Best,
Lukas

**Comment by lukasrothenberger** [comment]
Added to end-to-end tests in 39f4d262a88835b388531e45cf1f23f6653c1355
